spring.application.name=PaymentService
server.port=8083

otel.exporter.otlp.endpoint=http://otel-collector:4318
otel.service.name=PaymentService
otel.traces.exporter=otlp

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

