spring.application.name=order-service
server.port=8082

otel.exporter.otlp.endpoint=http://otel-collector:4318
otel.service.name=order-service
otel.traces.exporter=otlp

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always